name: Upstream Sync
permissions:
  contents: write
on:
  schedule:
    # 每8小时同步一次 (UTC 0, 8, 16点 / 北京时间 8, 16, 24点)
    - cron: '0 */12 * * *'
  # 保留手动触发按钮
  workflow_dispatch:
jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: github.event.repository.fork
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: LmeSzinc/AzurLaneAutoScript
          upstream_sync_branch: master
          target_sync_branch: merge-equip-fix # 请确认这是你想要同步的目标分支名
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
